export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const HABIT_GETALL_SUCCESS = 'HABIT_GETALL_SUCCESS'
export const HABIT_SELECT = 'HABIT_SELECT'
export const HABIT_UNSELECT = 'HABIT_UNSELECT'
