export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const HABIT_GETALL_SUCCESS = 'HABIT_GETALL_SUCCESS'
export const HABIT_GETALL_ERROR = 'HABIT_GETALL_ERROR'
export const HABIT_SELECT = 'HABIT_SELECT'
export const HABIT_UNSELECT = 'HABIT_UNSELECT'
