export const ERROR_MESSAGE = 'ERROR_MESSAGE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const HABIT_GET_ALL = 'HABIT_GET_ALL'

export const HABIT_GET_SELECTED_SUCCESS = 'HABIT_GET_SELECTED_SUCCESS'
export const HABIT_SELECT_SUCCESS = 'HABIT_SELECT_SUCCESS'
export const HABIT_DESELECT_SUCCESS = 'HABIT_DESELECT_SUCCESS'
